/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

/**
 *
 * @author Jamsterman25
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        MenuLabel1 = new javax.swing.JLabel();
        CheckoutButton = new javax.swing.JButton();
        RestockButton = new javax.swing.JButton();
        ManageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 600));

        MenuPanel.setPreferredSize(new java.awt.Dimension(550, 600));

        MenuLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(20, 80, 170));
        MenuLabel.setText("Welcome to the AutoScouts ");
        MenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuLabel.setMaximumSize(new java.awt.Dimension(320, 60));
        MenuLabel.setMinimumSize(new java.awt.Dimension(664, 30));
        MenuLabel.setPreferredSize(new java.awt.Dimension(664, 30));

        MenuLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        MenuLabel1.setForeground(new java.awt.Color(20, 80, 170));
        MenuLabel1.setText("Automated Checkout System");
        MenuLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuLabel1.setMaximumSize(new java.awt.Dimension(320, 60));
        MenuLabel1.setMinimumSize(new java.awt.Dimension(664, 30));
        MenuLabel1.setPreferredSize(new java.awt.Dimension(664, 30));

        CheckoutButton.setBackground(new java.awt.Color(135, 206, 250));
        CheckoutButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CheckoutButton.setText("Begin Checkout");

        RestockButton.setBackground(new java.awt.Color(135, 206, 250));
        RestockButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RestockButton.setText("Restock Items");

        ManageButton.setBackground(new java.awt.Color(135, 206, 250));
        ManageButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ManageButton.setText("Manage Items");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(MenuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(RestockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(RestockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CheckoutButton;
    public javax.swing.JButton ManageButton;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JLabel MenuLabel1;
    private javax.swing.JPanel MenuPanel;
    public javax.swing.JButton RestockButton;
    // End of variables declaration//GEN-END:variables
}
